import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import SessionWrapper from "@/components/atoms/SessionWrapper";
import ProtectedLayout from "@/components/atoms/ProtectedLayout";
import { ToastProvider } from "@/components/atoms/ToastProvider";
import { BranchProvider } from "@/context/BranchContext";

export const metadata: Metadata = {
  title: "DORA - Ecommerce Dashboard",
  description: "Generated by create next app",
  icons: {
    icon: [{ rel: "icon", url: "/images/logos/logo.png" }],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="font-sans antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem={true}
          disableTransitionOnChange
        >
          <ToastProvider>
            <SessionWrapper>
              <BranchProvider>
                <ProtectedLayout>{children}</ProtectedLayout>
              </BranchProvider>
            </SessionWrapper>
          </ToastProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
